### ISSUE TITLE
Build of a directory causes "Connection Reset by Peer" error

### ISSUE THREAD

**Issue by arunthampi** [convox/build#3]
The error and the relevant Dockerfile and docker-compose.yml are attached in the gist. Let me know if you guys need more information. Using docker 1.6.0 but master version of docker-compose cos I needed the `extra_hosts` feature which has not yet landed in a release.

https://gist.github.com/arunthampi/b9d763ade5d206f31986

**Comment by ddollar** [comment]
Does this happen every time for you?

**Comment by arunthampi** [comment]
Hmm yes, happened a couple of times, but just got this error:

https://gist.github.com/arunthampi/1689cd5d38745cbb35f9

It also seems to complain about `.env` being missing but it is present in the directory. Related question, while making the image, should `.env` have production values or are those injected later?

**Comment by ddollar** [comment]
Yes those will be injected later. Could you try removing the env_file stanzas from your docker-compose.yml?

**Comment by ddollar** [comment]
We probably need to upgrade our docker-compose inside convox/build as well to work with those extra stanzas. IIRC docker-compose fails on unrecognized config options.

**Comment by arunthampi** [comment]
Nope, removed both `env_file` and `extra_hosts` lines and have the same error. Did a fresh `docker-compose build` to see if that would change things. Here's the output from the command:

```
Cloning into '/tmp/repo556632210/clone'...
done.
manifest|web:
manifest|  build: .
manifest|  env_file: .env
manifest|  volumes:
manifest|    - ./:/gopath/src/github.com/mixcel/proxee/
manifest|  extra_hosts:
manifest|    - "mclovin.dev:127.0.0.1"
manifest|    - "fake-s3-deadbeef.dev:127.0.0.1"
manifest|  links:
manifest|    - dynamo
manifest|  ports:
manifest|    - "8080:8080"
manifest|
manifest|dynamo:
manifest|  image: convox/aws-dynamodb
packer|amazon-ebs output will be in this color.
packer|
packer|==> amazon-ebs: Inspecting the source AMI...
packer|==> amazon-ebs: Creating temporary keypair: packer 554930d8-c809-fe11-cc46-d99d83c5e370
packer|==> amazon-ebs: Creating temporary security group for this instance...
packer|==> amazon-ebs: Authorizing SSH access on the temporary security group...
packer|==> amazon-ebs: Launching a source AWS instance...
packer|==> amazon-ebs: Instance ID: i-2e5cdcf8
packer|==> amazon-ebs: Waiting for instance (i-2e5cdcf8) to become ready...
packer|==> amazon-ebs: Waiting for SSH to become available...
packer|==> amazon-ebs: Connected to SSH!
packer|==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell071663027
packer|==> amazon-ebs: Uploading /tmp/repo556632210/clone/ => /build
packer|==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell036644695
build|Couldn't find env file for service web: .env
packer|==> amazon-ebs: Terminating the source AWS instance...
packer|==> amazon-ebs: Deleting temporary security group...
packer|==> amazon-ebs: Deleting temporary keypair...
error|Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1
unknown|1430860142,,error-count,1
error|\n==> Some builds didn't complete successfully and had errors:
unknown|1430860142,amazon-ebs,error,Script exited with non-zero exit status: 1
error|--> amazon-ebs: Script exited with non-zero exit status: 1
packer|\n==> Builds finished but no artifacts were created.
error|exit status 1
```

**Comment by ddollar** [comment]
The manifest output at the top there is still showing `env_file` and `extra_hosts`

**Comment by arunthampi** [comment]
Ah sorry, realized I had to commit my changes for convox to get them.

**Comment by arunthampi** [comment]
yup that was it, built the AMI successfully after removing those stanzas and committing.

**Comment by ddollar** [comment]
Sweet. You can look at https://github.com/convox/architect if you want to try to make a cloudformation stack to boot your AMI.

If your app has only a web process, that would be:

    $ docker run convox/architect --processes=web --balancers=web

Anything specified in `--balancers` will get an ELB.

The resulting stack will have several parameters, most of which should be obvious.

The ones you need to fill out are:

* `AllowSSHFrom`: a CIDR mask from which to allow SSH access, see also `SSHKey`
* `AMI` the AMI you built with `convox/build`
* `Environment` a URL to an .env file, you can put this in the S3 bucket that the stack will create if you like
* `SSHKey`: the name of an ssh key on your account if you want to be able to ssh in
* `WebPorts`: map your web process to the ELB which wants port 3000. So if your docker container is listening for web on port 5000 this would be `3000:5000`

We are also working on a nice UI/CLI to tie all of this together automatically and I'll show you that tomorrow when we talk.

**Comment by arunthampi** [comment]
cool will try it out before the call tomorrow. I'm guessing I'll need to add a publicly accessible URL for ELBs to ping for health checks?

**Comment by ddollar** [comment]
Right now it will be pinging `/` but we’re thinking of changing it to `/check`

**Comment by arunthampi** [comment]
cool shall I close this and raise a separate issue about supporting the latest version of `docker-compose`.  Intending to use Docker as my dev env for this project if I can use the same in dev & prod.

**Comment by ddollar** [comment]
That sounds good
