### ISSUE TITLE
Add support for new docker-compose yaml directives

### ISSUE THREAD

**Issue by arunthampi** [convox/build#4]
Such as `env_file` and `extra_hosts`. If these stanzas are present in `docker-compose.yml` AMI building errors out. See https://github.com/convox/build/issues/3

**Comment by arunthampi** [comment]
Where can I update the version of `docker-compose` to master? afaik they haven't cut a release which adds support for `env_file` and `extra_hosts` so will have to build from src.

**Comment by ddollar** [comment]
https://github.com/convox/base/blob/master/data/packer.json#L62

**Comment by ddollar** [comment]
You'll want to get the master docker-compose there and build yourself a new base ami that you can plug in to convox/build

**Comment by arunthampi** [comment]
got it thanks.

**Comment by nzoschke** [comment]
We at least support env_file now. https://github.com/convox/build/blob/master/examples_test.go#L63

Not sure about extra_hosts... The manifest stuff has changed so much that I humbly request you open a new issue if it's not working with your app.
